export const USERS_REQUEST = "USERS_REQUEST";
export const POST_USERS_SUCCESS = "POST_USERS_SUCCESS";
export const CLEAR_USERS_LIST_SUCCESS = "CLEAR_USERS_LIST_SUCCESS";
export const REMOVE_USER_SUCCESS = "REMOVE_USER_SUCCESS";
export const EDIT_USER_ROLE_SUCCESS = "EDIT_USER_ROLE_SUCCESS";
export const USERS_FAILURE = "USERS_FAILURE";
