export const USER_REQUEST = "USER_REQUEST";
export const GET_USER_SERVICES_SUCCESS = "GET_USER_SERVICES_SUCCESS";
export const USER_FAILURE = "USER_FAILURE";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const ADD_SERVICE_TO_USER_SUCCESS = "ADD_SERVICE_TO_USER_SUCCESS";
