export const POST_POSTS_SUCCESS = "POST_POSTS_SUCCESS";
export const ADD_NEW_POST_SUCCESS = "ADD_NEW_POST_SUCCESS";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";
export const REMOVE_POST_SUCCESS = "REMOVE_POST_SUCCESS";
export const POSTS_REQUEST = "POSTS_REQUEST";
export const POSTS_FAILURE = "POSTS_FAILURE";
