export const POST_SERVICE_REQUEST = "POST_SERVICE_REQUEST";
export const POST_SERVICE_FAILURE = "POST_SERVICE_FAILURE";
export const POST_SERVICE_SUCCESS = "POST_SERVICE_SUCCESS";
export const ADD_SERVICE_TO_USER_REQUEST = "ADD_SERVICE_TO_USER_REQUEST";
export const ADD_SERVICE_TO_USER_SUCCESS = "ADD_SERVICE_TO_USER_SUCCESS";
export const ADD_SERVICE_TO_USER_FAILURE = "ADD_SERVICE_TO_USER_FAILURE";
